Repository fusionjs/fusion-plugin-browser-performance-emitter, pull requests merged in 2018-10, with the labels that each got.

#137 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#145 Add html resource data
  src/helpers/enhancedBrowserMetrics.js
Labels: bugfix

#143 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#147 Release v1.6.2-0
  package.json
Labels: release

#148 Release v1.7.0
  package.json
Labels: release
