Repository fusionjs/fusion-plugin-browser-performance-emitter, pull requests merged in 2018-11, with the labels that each got.

#152 Release v1.7.1
  package.json
Labels: release

#156 Send Emitter version
  package.json
  src/server.js
Labels: feature

#157 Release v1.7.2-2
  package.json
Labels: release

#158 Release v1.8.0
  package.json
Labels: release

#159 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
